source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

#gem 'neovim', '0.8.1'
gem 'ordinare'
#gem 'rails', '~> 6.0.3'
gem 'solargraph', '~>0.40.0'
#gem 'rubocop-rails'
gem 'rubocop'
